export const USER_SCHEDULE = "userSchedule";

const userScheduleSchema = {
  title: "userSchedule",
  description: "Daily schedule for the user, generated by the morning routine. Contains time-slotted plan for the day. One record per user per day (unique index on userId + date).",
  bsonType: "object",
  properties: {
    userId: {
      bsonType: "int",
      description: "Identifier for the user who owns this schedule"
    },

    date: {
      bsonType: "date",
      description: "The calendar date this schedule is for"
    },

    day: {
      bsonType: "string",
      enum: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      description: "Day of the week"
    },

    slots: {
      bsonType: "array",
      description: "Ordered list of time slots for the day",
      items: {
        bsonType: "object",
        properties: {
          slotId: {
            bsonType: "string",
            description: "Unique slot identifier within this schedule (e.g., 'slot_1', 'slot_2')"
          },
          startTime: {
            bsonType: "string",
            pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$",
            description: "Start time in HH:mm format"
          },
          endTime: {
            bsonType: "string",
            pattern: "^([01]\\d|2[0-3]):([0-5]\\d)$",
            description: "End time in HH:mm format"
          },
          title: {
            bsonType: "string",
            description: "Name or description of the scheduled activity"
          },
          category: {
            bsonType: ["string", "null"],
            description: "Category: Work, Personal, Health, Finance, etc."
          },
          taskRef: {
            bsonType: ["string", "null"],
            description: "Reference _id from taskCalendar if this slot is linked to a pending task"
          },
          priority: {
            bsonType: ["string", "null"],
            enum: ["Low", "Medium", "High", null]
          },
          status: {
            bsonType: "string",
            enum: ["Planned", "InProgress", "Done", "Skipped", "Rescheduled"],
            description: "Current status of this time slot"
          },
          notes: {
            bsonType: ["string", "null"],
            description: "Any extra context or details for this slot"
          }
        },
        required: ["slotId", "startTime", "endTime", "title", "status"]
      }
    },

    summary: {
      bsonType: ["string", "null"],
      description: "Brief summary of the day plan"
    },

    motivationalNote: {
      bsonType: ["string", "null"],
      description: "Motivational message for the day"
    },

    createdAt: {
      bsonType: "date"
    },

    updatedAt: {
      bsonType: "date"
    }
  },
  required: ["userId", "date", "day", "slots"]
};

export default userScheduleSchema;

/**
 * Serves:
 *  - insertTodaySchedule — findOne({ userId, date: {$gte,$lt} }) on every
 *    calendar sync
 *
 * unique: the collection description and insertSchedule's own comment both
 * already claim "one record per user per day (unique index on userId + date)".
 * The index was never actually created, so a second lock-in for the same day
 * silently inserted a rival schedule and the calendar sync picked whichever
 * findOne returned first.
 */
export const USER_SCHEDULE_INDEXES = [
  { key: { userId: 1, date: -1 }, name: "userId_1_date_-1", unique: true },
];
